version: '3'

services:
  web:
    container_name: web
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./environments/.env.development
    labels:
      traefik.enable: true
      traefik.http.routers.web.rule: Host(`web.localhost`)
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "./services/traefik/traefik.development.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
  db:
    container_name: db
    image: postgres:alpine
    volumes:
      - postgres_data_development:/var/lib/postgresql/data/
    env_file:
      - ./environments/.env.db.development
    restart: unless-stopped

volumes:
  postgres_data_development:
